version: '3.8'

services:
  fastapi_backend:
    container_name: fastapi_backend
    build: ./
    image: fastapi/backend:0.1
    restart: unless-stopped
    ports:
      - "9001:9001"
    networks:
      - example_platform

networks:
  example_platform:
    name: example_platform
